Fix CAMR_advance.cpp: include PS_relaxation.H under USE_PS_HYDRO
Missing include left ps_apply_relaxation() undeclared when Phase
4d landed.  Reported build error:
    Source/CAMR_advance.cpp:169:9: error: use of undeclared
    identifier 'ps_apply_relaxation'